define([], function() {
  return {
    'titlePlaceholder': 'タイトル',
    'emptyDropDownPlaceholder': '(未選択)',
    'endpointPlaceholder': 'APIエンドポイントURL',
    'executeButtonText': '実行',
    'requestBodyPivotLabel': '要求本文',
    'requestBodyPlaceholder': 'JSON文字列を記述します。',
    'requestHeadersPivotLabel': '要求ヘッダ',
    'requestHeadersKeyText': 'キー',
    'requestHeadersValueText': '値',
    'requestHeaderKeyPlaceholder': 'キー',
    'requestHeaderValuePlaceholder': '値',
    'requestHeaderRowDeleteButtonTtitle': '削除',
    'responseBodyPivotLabel': '応答本文',
    'responseHeadersPivotLabel': '応答ヘッダ',
    'presetRequestButtonTitle': 'サンプルリクエスト',
    'presetRequestDialogTitle': 'サンプルリクエスト',
    'presetRequestEnvironmentCategory': '環境',
    'presetRequestListEnvironmentTitle': '一覧',
    'presetRequestListEnvironmentDescription': '環境の一覧を取得します。',
    'presetRequestEntityCategory': 'エンティティ',
    'presetRequestListEntityTitle': '一覧',
    'presetRequestListEntityDescription': 'エンティティの一覧を取得します。',
    'presetRequestGetEntityTitle': '取得',
    'presetRequestGetEntityDescription': '指定したエンティティの詳細を取得します。このサンプルでは「accounts」エンティティを取得します。',
  }
});