define([], function() {
  return {
    'titlePlaceholder': 'Title',
    'emptyDropDownPlaceholder': '(Not selected)',
    'endpointPlaceholder': 'End point url',
    'executeButtonText': 'Execute',
    'requestBodyPivotLabel': 'Request body',
    'requestBodyPlaceholder': 'Input JSON string hear.',
    'requestHeadersPivotLabel': 'Request headers',
    'requestHeadersKeyText': 'Key',
    'requestHeadersValueText': 'Value',
    'requestHeaderKeyPlaceholder': 'Key',
    'requestHeaderValuePlaceholder': 'Value',
    'requestHeaderRowDeleteButtonTtitle': 'Delete',
    'responseBodyPivotLabel': 'Response body',
    'responseHeadersPivotLabel': 'Response header',
    'presetRequestButtonTitle': 'Preset requests',
    'presetRequestDialogTitle': 'Preset requests',
    'presetRequestEnvironmentCategory': 'Environment',
    'presetRequestListEnvironmentTitle': 'LIST',
    'presetRequestListEnvironmentDescription': 'List your Dataflex Pro environments.',
    'presetRequestEntityCategory': 'Entity',
    'presetRequestListEntityTitle': 'LIST',
    'presetRequestListEntityDescription': 'List your Dataflex Pro entities.',
    'presetRequestGetEntityTitle': 'GET',
    'presetRequestGetEntityDescription': 'Get the metadata of the specific entity.This sample works for the Accounts entity.',
  }
});